// GENERATED by `bun run i18n:compile` from locales/en.po — DO NOT EDIT.
//
// Freshness is enforced by `bun run i18n:catalog:check`, which recompiles the
// .po and compares bytes. Edit locales/en.po and recompile instead.
//
// Untranslated and fuzzy entries are deliberately ABSENT rather than present as
// empty strings: a lookup miss falls back to the msgid, which is the English
// source text (ADR-0095).
import type { CompiledCatalog } from "../catalog";

export const EN_CATALOG: CompiledCatalog = {
  "Cek status": ["Check status"]
};
