#!/usr/bin/env bun
/**
 * jobs:env-allowlist — render the set of environment variables a scheduled job
 * container must receive, from the variables the code ACTUALLY reads.
 *
 * ## Why this exists
 *
 * `ops/run-job.sh` copies env out of the running app container and into the job
 * container. It used to select what to copy with a hand-maintained prefix
 * pattern:
 *
 *     grep -E '^(DATABASE_URL|WORKER_DATABASE_URL|…|CLOUDFLARE_|EDGE_CACHE_)'
 *
 * Measured against `collectEnvReads()` at the time this landed, that pattern
 * dropped **81 of the 171** variables this codebase reads. Not ten. Among them:
 *
 * - `DATA_LIFECYCLE_ARCHIVE_ROOT_PATH` and `REPORTING_EXPORT_ROOT_PATH` — the
 *   two paths that decide WHERE a job writes the artefact a database row then
 *   claims exists;
 * - every `TENANT_DOMAIN_CLOUDFLARE_*` variable, because `^CLOUDFLARE_` is
 *   anchored and those do not start with it — so `tenant-domain:dns:sync` ran
 *   with no API token and no zone;
 * - every `VISITOR_ANALYTICS_*` variable, including the retention windows that
 *   `analytics:purge` exists to enforce;
 * - `SYNC_HMAC_ALLOW_LEGACY`, `SITE_SEARCH_*`, `TURNSTILE_*`, `TRUSTED_PROXY_*`.
 *
 * A job missing a variable does not fail. It takes the code's default, which is
 * usually the safe-but-inert one, and reports success — the shape this repo has
 * shipped before and keeps finding.
 *
 * ## Why a generated allow-list and not a deny-list
 *
 * The file lands on a host and is read into a `0600` temp file, so what it names
 * is worth bounding. But the bound must not be a hand-kept guess: the failure
 * that matters here is a variable MISSING, and a hand-kept pattern goes stale on
 * the day somebody adds one. Generating it from the same source
 * `config:env:coverage:check` uses means the list cannot fall behind the code
 * without a gate going red.
 *
 * `TOOLING_ONLY` names are excluded: they belong to build/CI tooling and no job
 * process reads them, which is the same reason the coverage gate exempts them.
 *
 * Usage:
 *   bun run jobs:env-allowlist:generate
 *   bun run jobs:env-allowlist:check
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import {
  TOOLING_ONLY,
  collectEnvReads
} from "./env-contract-coverage-check.ts";

const ROOT = process.cwd();
const OUTPUT = "ops/awcms-jobs.env-allowlist";
const CHECK_ONLY = process.argv.includes("--check");

const HEADER = [
  "# GENERATED by `bun run jobs:env-allowlist:generate` — do not edit by hand.",
  "#",
  "# Every environment variable this codebase reads, minus the tooling-only ones",
  "# no job process touches. `ops/run-job.sh` copies exactly these out of the",
  "# running app container and into the job container.",
  "#",
  "# It is generated rather than written because the failure mode is a variable",
  "# MISSING: a job that does not receive one takes the code's default, does the",
  "# inert thing, and reports success. The prefix pattern this replaced dropped 81",
  "# of 171 — including both artefact-root paths, every TENANT_DOMAIN_CLOUDFLARE_*",
  "# variable, and every VISITOR_ANALYTICS_* retention window.",
  "#",
  "# One name per line. Blank lines and `#` comments are ignored by the reader.",
  ""
].join("\n");

/** Sorted, so a diff shows what changed rather than where the walker happened to go. */
export function renderAllowlist(names: readonly string[]): string {
  return `${HEADER}${[...names].sort().join("\n")}\n`;
}

export async function collectJobEnvNames(): Promise<string[]> {
  const reads = await collectEnvReads();
  const toolingOnly = new Set(TOOLING_ONLY.map((entry) => entry.name));

  return [...reads.keys()].filter((name) => !toolingOnly.has(name)).sort();
}

async function main(): Promise<void> {
  const names = await collectJobEnvNames();

  // A generator that walks nothing renders an EMPTY allow-list, and an empty
  // allow-list makes every job run with no database URL — a failure that looks
  // like an outage rather than like a broken generator. This repo has shipped a
  // gate that passed while scanning zero files; it does not need a generator
  // that ships zero lines.
  if (names.length < 50) {
    console.error(
      `jobs:env-allowlist FAILED — only ${names.length} environment variable(s) found. ` +
        "Run this from the repository root; a near-empty allow-list would strip a job's " +
        "entire configuration and the job would still report success."
    );
    process.exit(1);
  }

  const rendered = renderAllowlist(names);
  const outputPath = path.join(ROOT, OUTPUT);

  if (CHECK_ONLY) {
    let current: string | null = null;
    try {
      current = readFileSync(outputPath, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }

    if (current !== rendered) {
      console.error(
        `jobs:env-allowlist:check FAILED — ${OUTPUT} is ${current === null ? "missing" : "stale"}.\n` +
          "  Run `bun run jobs:env-allowlist:generate` and commit the result.\n" +
          "  A stale list means a scheduled job runs without a variable it reads,\n" +
          "  takes the default, and reports success."
      );
      process.exit(1);
    }

    console.log(
      `jobs:env-allowlist:check OK — ${OUTPUT} names ${names.length} variable(s), matching a fresh regeneration.`
    );
  } else {
    writeFileSync(outputPath, rendered);
    console.log(
      `jobs:env-allowlist — wrote ${OUTPUT} (${names.length} variable(s)).`
    );
  }
}

if (import.meta.main) {
  await main();
}
