/**
 * The `scripts/README.md` inventory, derived from `package.json`.
 *
 * ## Why generated
 *
 * The table it replaces was hand-written, and it aged in the direction that
 * does the most damage. It listed 12 of 52 scripts as "active", and its
 * companion "not yet ported" table named fifteen tools that had not only
 * landed but were IN the `bun run check` chain — `api:docs:check`,
 * `modules:compose:check`, `db:work-class:check`, and every per-module worker.
 *
 * A negative claim is the dangerous kind: "X does not exist yet" gets more
 * wrong with time and never fails on its own, unlike a positive claim that
 * breaks the moment the code moves. Someone reading it would conclude
 * `db:work-class:check` still needed building and build a second one.
 *
 * So the completeness half is derived and the prose half is not: this file
 * generates target/script/in-check, which is exactly the part that goes stale,
 * and leaves the rest of the README to a human.
 *
 * Two commands, one source: `bun run scripts:inventory:generate` rewrites the
 * marked block, `bun run scripts:inventory:check` fails if it is out of date.
 * A `.generated` artefact WITHOUT that pair is a false claim that reads more
 * authoritative than prose.
 *
 * ## Why the check normalizes instead of comparing bytes
 *
 * Prettier owns markdown formatting here and pads table columns to align them.
 * A byte-for-byte comparison would therefore fail immediately after every
 * `bun run lint`, and the two would fight forever. So the check NORMALIZES the
 * block — dropping exactly what prettier rewrites, which is column padding and
 * the dashes in the separator row — and compares the rest. Padding is not
 * drift.
 *
 * ## Why it normalizes the WHOLE block and not just the rows
 *
 * It used to compare only the rows, and that let the block go half-stale in a
 * way nobody could see: the counts sentence above the table was generated and
 * never checked. Issue #442 is how it actually happened, and git wrote it, not
 * a human. Two PRs branched from the same base, each adding one target; both
 * regenerated, so both turned `77 … 31` into the IDENTICAL text `78 … 32`.
 * Rebasing the second onto the first found no conflict on a line where the two
 * sides agreed, merged the differing table rows into 79, and produced a block
 * whose table was right and whose sentence was wrong.
 *
 * That is the direction worth noticing: the old comparison covered exactly the
 * part git CANNOT silently merge wrong (differing rows either conflict or union
 * correctly) and skipped the part it can (identical lines whose meaning
 * changed). So the unit of comparison is the block, and anything the generator
 * writes is covered by construction — including whatever it is taught to write
 * next.
 */
const README_PATH = "scripts/README.md";
const BEGIN = "<!-- BEGIN GENERATED: script-inventory -->";
const END = "<!-- END GENERATED: script-inventory -->";

/**
 * Both language copies (Issue #727).
 *
 * This generator wrote `scripts/README.md` only, while `scripts/README.id.md`
 * carried the SAME block — banner included, telling the reader not to hand-edit
 * a block that nothing generated. It drifted to "107 target / 48 gerbang"
 * against a real 121/54.
 *
 * `check:docs:translation` cannot see it: it hashes the ENGLISH source and
 * compares against a marker in the mirror, which answers "has the English
 * changed since this was translated?" — the right question for prose, and the
 * wrong one for content derived from the repo, which goes stale while both
 * files sit untouched.
 *
 * The table is language-neutral (targets and file names are not translated), so
 * only the banner, the count sentence and the three column headers differ.
 */
export type InventoryLocale = "en" | "id";

type LocaleStrings = {
  readmePath: string;
  banner: string;
  countSentence: (total: number, gated: number) => string[];
  header: string[];
};

const LOCALES: Record<InventoryLocale, LocaleStrings> = {
  en: {
    readmePath: "scripts/README.md",
    banner:
      "<!-- Generated by `bun run scripts:inventory:generate`. DO NOT hand-edit. -->",
    countSentence: (total, gated) => [
      `${total} targets run a file in \`scripts/\`; ${gated} of them are`,
      "in the `bun run check` chain (the **Gate** column); the rest are run manually,",
      "scheduled, or by a specific CI workflow."
    ],
    header: ["| Target | Script | Gate |", "| ------ | ----- | ---- |"]
  },
  id: {
    readmePath: "scripts/README.id.md",
    banner:
      "<!-- Dihasilkan `bun run scripts:inventory:generate`. JANGAN diedit tangan. -->",
    countSentence: (total, gated) => [
      `${total} target menjalankan berkas di \`scripts/\`; ${gated} di antaranya`,
      "ada di rantai `bun run check` (kolom **Gate**), sisanya dijalankan manual,",
      "terjadwal, atau oleh workflow CI tertentu."
    ],
    header: ["| Target | Script | Gate |", "| ------ | ----- | ---- |"]
  }
};

export const INVENTORY_LOCALES = Object.keys(LOCALES) as InventoryLocale[];

export function inventoryReadmePath(locale: InventoryLocale): string {
  return LOCALES[locale].readmePath;
}

export type InventoryRow = {
  target: string;
  script: string;
  inCheck: boolean;
};

export type PackageScripts = Record<string, string>;

const SCRIPT_REFERENCE = /scripts\/([\w.-]+\.(?:ts|mjs))/;

/**
 * One row per `package.json` target that runs a file in `scripts/`. Targets
 * that only compose other targets (`check` itself, `dev`, `build`) are not
 * inventory entries — they run no script of their own.
 */
export function buildInventory(packageScripts: PackageScripts): InventoryRow[] {
  const chain = packageScripts.check ?? "";

  return Object.entries(packageScripts)
    .flatMap(([target, command]) => {
      const match = command.match(SCRIPT_REFERENCE);
      if (!match) return [];

      return [
        {
          target,
          script: match[1]!,
          inCheck:
            chain.includes(`bun run ${target} `) ||
            chain.endsWith(`bun run ${target}`)
        }
      ];
    })
    .sort((a, b) => a.target.localeCompare(b.target));
}

export function renderInventory(
  rows: readonly InventoryRow[],
  locale: InventoryLocale = "en"
): string {
  const gated = rows.filter((row) => row.inCheck).length;
  const t = LOCALES[locale];

  return [
    BEGIN,
    "",
    t.banner,
    "",
    ...t.countSentence(rows.length, gated),
    "",
    ...t.header,
    ...rows.map(
      (row) =>
        `| \`${row.target}\` | \`${row.script}\` | ${row.inCheck ? "✅" : "—"} |`
    ),
    "",
    END
  ].join("\n");
}

export function replaceInventoryBlock(
  readme: string,
  rendered: string,
  readmePath: string = README_PATH
): string {
  const begin = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);

  if (begin === -1 || end === -1) {
    throw new Error(
      `${readmePath} is missing the ${BEGIN} / ${END} markers — the generated block has no home.`
    );
  }

  return readme.slice(0, begin) + rendered + readme.slice(end + END.length);
}

/** Parses the rendered block back into rows, ignoring column padding. */
export function parseInventoryBlock(block: string): InventoryRow[] {
  return block
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.startsWith("| `"))
    .map((line) => {
      const cells = line
        .split("|")
        .slice(1, -1)
        .map((cell) => cell.trim().replace(/^`|`$/g, ""));

      return {
        target: cells[0] ?? "",
        script: cells[1] ?? "",
        inCheck: cells[2] === "✅"
      };
    });
}

/**
 * The block reduced to what the generator DECIDED, with what prettier decides
 * removed: blank lines, column padding, and the separator row whose dashes are
 * stretched to match the widest cell.
 *
 * Everything else survives — so the counts sentence, and any future prose the
 * generator emits, is compared without anyone having to remember to add it.
 */
export function normalizeInventoryBlock(block: string): string {
  return block
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .filter((line) => !/^\|[\s|:-]+\|$/.test(line))
    .map((line) =>
      line.startsWith("|")
        ? line
            .split("|")
            .map((cell) => cell.trim())
            .join("|")
        : line
    )
    .join("\n");
}

export function extractInventoryBlock(
  readme: string,
  readmePath: string = README_PATH
): string {
  const begin = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);

  if (begin === -1 || end === -1) {
    throw new Error(`${readmePath} is missing the generated-block markers.`);
  }

  return readme.slice(begin, end + END.length);
}

/**
 * A target named as "not yet ported" that actually EXISTS. This is the exact
 * shape of the failure: the claim is negative, so nothing breaks when it stops
 * being true.
 */
export function findFalseAbsenceClaims(
  readme: string,
  packageScripts: PackageScripts
): string[] {
  const deferredHeading = readme.indexOf("## Deferred");
  if (deferredHeading === -1) return [];

  // TABLE ROWS only. The prose in that section explains the rule and names a
  // real target while doing so; scanning it wholesale made the gate report
  // itself on its first run — the same self-report `table-write-ownership-check`
  // and `tenant-context-usage-check` both hit.
  const rows = readme
    .slice(deferredHeading)
    .split("\n")
    .filter((line) => line.trimStart().startsWith("|"))
    .join("\n");

  return Object.keys(packageScripts)
    .filter((target) => rows.includes(`\`${target}\``))
    .sort();
}

export async function readPackageScripts(): Promise<PackageScripts> {
  return (
    (await Bun.file("package.json").json()) as { scripts: PackageScripts }
  ).scripts;
}

async function main(): Promise<void> {
  const mode = process.argv.includes("--check") ? "check" : "generate";
  const packageScripts = await readPackageScripts();
  // One build, rendered per locale. Building per locale would let the two
  // copies disagree about a package.json that did not change between them.
  const expected = buildInventory(packageScripts);
  const failures: string[] = [];

  for (const locale of INVENTORY_LOCALES) {
    const readmePath = inventoryReadmePath(locale);
    const readme = await Bun.file(readmePath).text();
    const rendered = renderInventory(expected, locale);

    if (mode === "generate") {
      await Bun.write(
        readmePath,
        replaceInventoryBlock(readme, rendered, readmePath)
      );
      console.log(
        `Updated: ${readmePath} — the script inventory block was regenerated.`
      );
      continue;
    }

    const block = extractInventoryBlock(readme, readmePath);
    const present = parseInventoryBlock(block);

    // Rows first, because that message can name a useful number.
    if (JSON.stringify(present) !== JSON.stringify(expected)) {
      failures.push(
        `${readmePath} does not match a fresh render from package.json ` +
          `(${present.length} rows recorded vs ${expected.length} real targets). ` +
          "Run `bun run scripts:inventory:generate` and commit the result."
      );
    } else if (
      normalizeInventoryBlock(block) !== normalizeInventoryBlock(rendered)
    ) {
      // Rows match, block does not: what is stale sits OUTSIDE the table —
      // today the count sentence (#442). The message says so, because
      // "just regenerate" without naming the difference is how this was
      // missed the first time.
      failures.push(
        `${readmePath}: the rows match but the generated block does NOT — ` +
          "what is stale sits outside the table (the count sentence above it). " +
          "Run `bun run scripts:inventory:generate` and commit the result."
      );
    }

    // The false-absence scan reads prose, so it is per-document by nature.
    for (const claim of findFalseAbsenceClaims(readme, packageScripts)) {
      failures.push(`${readmePath}: ${claim}`);
    }
  }

  if (mode === "generate") {
    return;
  }

  if (failures.length > 0) {
    console.error("scripts:inventory:check FAILED");
    for (const failure of failures) {
      console.error(`  - ${failure}`);
    }
    process.exitCode = 1;
    return;
  }

  console.log(
    `scripts:inventory:check OK — the inventory block matches in all ${INVENTORY_LOCALES.length} language copies, and no target that exists is claimed to be missing.`
  );
}

if (import.meta.main) {
  await main();
}
