import { serializeJsonForScriptElement } from "../../../lib/html/escape";

/**
 * The contract between the editor preview ROUTE and the browser overlay that
 * edits it (Issue #592).
 *
 * Two constants and one serializer, in a pure module, because the two halves
 * run in different places and cannot import each other: the route is server
 * code and `src/lib/ui/blog-preview-overlay.ts` is bundled for the browser.
 * Hand-copying an element id into client code is a rename away from an overlay
 * that finds nothing — and "nothing is clickable" is a failure nobody files as
 * a bug.
 *
 * Pure module: no database, no DOM, no I/O.
 */

/** The `<script type="application/json">` element the overlay reads its state from. */
export const PREVIEW_STATE_ELEMENT_ID = "blog-preview-editor-state";

/**
 * The bundled overlay, generated by `bun run build:preview-overlay` and served
 * from `public/`.
 *
 * It has to come from `public/` because `preview.ts` is an `APIRoute` returning
 * an HTML string and Astro only bundles `<script>` for `.astro` components.
 * Declared `app` in `PUBLIC_ASSET_AUDIENCE` (ADR-0101): a reader never loads
 * this, and charging it to the reader budget would misreport the tightest
 * ceiling in the repo.
 */
export const PREVIEW_OVERLAY_SCRIPT_SRC = "/js/blog-preview-overlay.js";

/**
 * The overlay's state block plus the tag that loads it.
 *
 * ## Why the document is EMBEDDED rather than fetched
 *
 * The overlay needs the canonical Portable Text array to splice an edited block
 * into — it cannot recover it from the rendered HTML, and it must not try:
 * `renderPortableTextToHtml` emits `<a href>` where the editor's own editable
 * form uses `<a data-mark>`, so a round trip through the DOM would need a
 * second, subtly different parser. Reading it from a `GET` would also make this
 * screen depend on `blog_content.posts.read`, which it deliberately does not
 * hold: the whole page is gated on `posts.update`.
 *
 * It is the same content the page already renders, so embedding it discloses
 * nothing the reader of this page cannot already see.
 *
 * ## Why `type="application/json"` is not blocked by CSP
 *
 * A `<script>` whose type is not a JavaScript MIME type is a DATA BLOCK: the
 * HTML parser never executes it, and `script-src` does not apply. The same
 * mechanism already carries `application/ld+json` on every public article under
 * this app's `default-src 'self'` policy. The overlay ITSELF is an external
 * same-origin module, which `'self'` admits.
 */
export function renderPreviewOverlayHtml(
  postId: string,
  body: unknown
): string {
  const state = serializeJsonForScriptElement({ postId, document: body });

  return `
<script type="application/json" id="${PREVIEW_STATE_ELEMENT_ID}">${state}</script>
<script type="module" src="${PREVIEW_OVERLAY_SCRIPT_SRC}"></script>`;
}
