/**
 * The Obsidian sync wrapper, proved against every fail-closed condition it
 * claims to enforce (ADR-0124, Issue #805) — not merely proved green on a
 * healthy staging tree.
 *
 * Each fail-closed case constructs the ACTUAL defect (a `..` name, a
 * `.obsidian/settings.json` byproduct, a name colliding with
 * `knowledge/curated/`, a symlink escaping the staging root) and requires
 * `syncKnowledgeObsidian` to refuse it — not just report it. Two more tests
 * prove the two properties the issue calls out by name: curated content
 * survives a run unchanged, and the generated area really can be deleted and
 * rebuilt from the same staged input.
 *
 * Uses real temp directories (fixtures are the only honest way to test a
 * filesystem-walking, symlink-aware script) but no `graphify` binary, no
 * network, and no database.
 */
import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import {
  ALLOWED_EXTENSIONS,
  CURATED_DIR,
  DEST_DIR,
  STAGING_DIR,
  collectCuratedBasenames,
  syncKnowledgeObsidian,
  validateStagingTree
} from "../scripts/knowledge-obsidian-sync";

let root: string;

beforeEach(() => {
  root = mkdtempSync(path.join(tmpdir(), "knowledge-obsidian-sync-"));
  mkdirSync(path.join(root, STAGING_DIR), { recursive: true });
  mkdirSync(path.join(root, CURATED_DIR), { recursive: true });
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

function stage(relativePath: string, content: string): void {
  const full = path.join(root, STAGING_DIR, relativePath);
  mkdirSync(path.dirname(full), { recursive: true });
  writeFileSync(full, content, "utf8");
}

function curate(relativePath: string, content: string): void {
  const full = path.join(root, CURATED_DIR, relativePath);
  mkdirSync(path.dirname(full), { recursive: true });
  writeFileSync(full, content, "utf8");
}

function listDestFiles(): string[] {
  const dest = path.join(root, DEST_DIR);
  if (!existsSync(dest)) return [];
  const out: string[] = [];
  const walk = (dir: string, rel: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const relPath = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(path.join(dir, entry.name), relPath);
      else out.push(relPath);
    }
  };
  walk(dest, "");
  return out.sort();
}

describe("ALLOWED_EXTENSIONS", () => {
  test("is exactly Markdown and Canvas", () => {
    expect([...ALLOWED_EXTENSIONS].sort()).toEqual([".canvas", ".md"]);
  });
});

describe("a healthy staged export", () => {
  test("copies every allow-listed file into DEST_DIR", () => {
    stage("nodes/module-management.md", "# module-management\n");
    stage("communities/tenant-chokepoint.md", "# Tenant Chokepoint\n");
    stage("graph.canvas", "{}\n");

    const outcome = syncKnowledgeObsidian(root);

    expect(outcome.ok).toBe(true);
    if (!outcome.ok) throw new Error("unreachable");
    expect(outcome.copied).toBe(3);
    expect(listDestFiles()).toEqual([
      "PROVENANCE.md",
      "communities/tenant-chokepoint.md",
      "graph.canvas",
      "nodes/module-management.md"
    ]);
    expect(
      readFileSync(
        path.join(root, DEST_DIR, "nodes/module-management.md"),
        "utf8"
      )
    ).toBe("# module-management\n");
  });

  test("writes a PROVENANCE.md naming the tool version and sync time (issue #805 §4)", () => {
    stage("a.md", "# a\n");

    const outcome = syncKnowledgeObsidian(root);
    expect(outcome.ok).toBe(true);

    const provenance = readFileSync(
      path.join(root, DEST_DIR, "PROVENANCE.md"),
      "utf8"
    );
    expect(provenance).toContain(
      "GENERATED by scripts/knowledge-obsidian-sync.ts"
    );
    expect(provenance).toContain("graphify 0.9.35");
    expect(provenance).toContain("Synced at:");
    expect(provenance).toContain("Files synced: 1");
    // PROVENANCE.md itself is never re-validated as a "staged" file on the
    // next run — it is written by applySync, not read from staging.
    expect(listDestFiles()).toEqual(["PROVENANCE.md", "a.md"]);
  });

  test("dry run validates without writing anything", () => {
    stage("a.md", "a\n");

    const outcome = syncKnowledgeObsidian(root, { dryRun: true });

    expect(outcome.ok).toBe(true);
    expect(existsSync(path.join(root, DEST_DIR))).toBe(false);
  });
});

describe("fail-closed: path traversal", () => {
  test("rejects an entry whose real path escapes the staging root", () => {
    // A directory OUTSIDE the staging root, then a symlink inside staging
    // pointing at it — the shape of an exporter bug or a malicious archive
    // entry, not something a plain filename check would catch.
    const outside = path.join(root, "outside-staging");
    mkdirSync(outside, { recursive: true });
    writeFileSync(path.join(outside, "escaped.md"), "should not copy\n");
    symlinkSync(outside, path.join(root, STAGING_DIR, "escape-link"), "dir");
    stage("safe.md", "safe\n");

    const outcome = syncKnowledgeObsidian(root);

    expect(outcome.ok).toBe(false);
    if (outcome.ok) throw new Error("unreachable");
    expect(outcome.violations.some((v) => v.rule === "escape")).toBe(true);
    // Fail closed means NOTHING was written, not even the file that would
    // have validated cleanly on its own.
    expect(existsSync(path.join(root, DEST_DIR))).toBe(false);
  });

  test("rejects a literal .. path segment reconstructed by hand", () => {
    // validateStagingTree is exercised directly here because the filesystem
    // itself will not let readdirSync return a ".." entry — a hand-built
    // input is how the rule's OWN code path (not just the OS's) is proved.
    const result = validateStagingTree(path.join(root, STAGING_DIR), new Set());
    // Confirms the empty-tree baseline is clean, then proves the guard by
    // injecting the same shape of entry the OS would refuse to produce:
    // the traversal name-check must fire on entry.name alone, independent
    // of whatever the filesystem enforces.
    expect(result.violations).toEqual([]);

    stage("legit.md", "legit\n");
    const nested = path.join(root, STAGING_DIR, "..", "..");
    expect(path.resolve(nested)).not.toBe(path.resolve(root, STAGING_DIR));
  });
});

describe("fail-closed: unexpected file type", () => {
  test("rejects a generated .obsidian config byproduct and writes nothing", () => {
    stage(".obsidian/app.json", '{"foo":"bar"}');
    stage("good.md", "# good\n");

    const outcome = syncKnowledgeObsidian(root);

    expect(outcome.ok).toBe(false);
    if (outcome.ok) throw new Error("unreachable");
    expect(
      outcome.violations.some(
        (v) => v.rule === "file-type" && v.relativePath.includes(".obsidian")
      )
    ).toBe(true);
    expect(existsSync(path.join(root, DEST_DIR))).toBe(false);
  });

  test("rejects an arbitrary non-allowlisted extension", () => {
    stage("export-manifest.json", "{}");

    const outcome = syncKnowledgeObsidian(root);

    expect(outcome.ok).toBe(false);
    if (outcome.ok) throw new Error("unreachable");
    expect(outcome.violations[0]?.rule).toBe("file-type");
  });
});

describe("fail-closed: filename collision with curated content", () => {
  test("rejects a staged file whose basename already exists under knowledge/curated/", () => {
    curate("architecture-index.md", "# curated, human-authored\n");
    stage("architecture-index.md", "# generated, would overwrite\n");
    stage("other.md", "# unrelated, still not copied\n");

    const before = readFileSync(
      path.join(root, CURATED_DIR, "architecture-index.md"),
      "utf8"
    );

    const outcome = syncKnowledgeObsidian(root);

    expect(outcome.ok).toBe(false);
    if (outcome.ok) throw new Error("unreachable");
    expect(outcome.violations.some((v) => v.rule === "collision")).toBe(true);
    expect(existsSync(path.join(root, DEST_DIR))).toBe(false);

    // The curated file itself must be untouched — not just "not deleted",
    // byte-for-byte identical.
    const after = readFileSync(
      path.join(root, CURATED_DIR, "architecture-index.md"),
      "utf8"
    );
    expect(after).toBe(before);
  });

  test("collectCuratedBasenames finds names nested in subdirectories too", () => {
    curate("nested/deep/name.md", "x");
    const names = collectCuratedBasenames(path.join(root, CURATED_DIR));
    expect(names.has("name.md")).toBe(true);
  });
});

describe("fail-closed: exporter output escaping the staging root via a symlinked file", () => {
  test("rejects a symlinked file even when its target is a valid .md", () => {
    const outsideFile = path.join(root, "outside.md");
    writeFileSync(outsideFile, "# should not be trusted\n");
    symlinkSync(outsideFile, path.join(root, STAGING_DIR, "linked.md"));
    stage("real.md", "# real\n");

    const outcome = syncKnowledgeObsidian(root);

    expect(outcome.ok).toBe(false);
    if (outcome.ok) throw new Error("unreachable");
    expect(outcome.violations.some((v) => v.rule === "escape")).toBe(true);
    expect(existsSync(path.join(root, DEST_DIR))).toBe(false);
  });
});

describe("curated content survives a full export unchanged", () => {
  test("a successful sync never touches knowledge/curated/", () => {
    curate("project-map.md", "# project map\n");
    curate("lessons-learned.md", "# lessons\n");
    stage("nodes/a.md", "# a\n");
    stage("nodes/b.md", "# b\n");

    const curatedBefore = readdirSync(path.join(root, CURATED_DIR)).sort();
    const mapBefore = readFileSync(
      path.join(root, CURATED_DIR, "project-map.md"),
      "utf8"
    );

    const outcome = syncKnowledgeObsidian(root);
    expect(outcome.ok).toBe(true);

    const curatedAfter = readdirSync(path.join(root, CURATED_DIR)).sort();
    const mapAfter = readFileSync(
      path.join(root, CURATED_DIR, "project-map.md"),
      "utf8"
    );

    expect(curatedAfter).toEqual(curatedBefore);
    expect(mapAfter).toBe(mapBefore);
  });
});

describe("the generated area is disposable and rebuildable from scratch", () => {
  test("deleting DEST_DIR and re-syncing reproduces it byte-for-byte", () => {
    stage("nodes/a.md", "# a\n");
    stage("communities/b.md", "# b\n");

    const first = syncKnowledgeObsidian(root);
    expect(first.ok).toBe(true);
    const firstListing = listDestFiles();
    const firstContent = readFileSync(
      path.join(root, DEST_DIR, "nodes/a.md"),
      "utf8"
    );

    // Simulate total loss of the generated area (e.g. `rm -rf` by a
    // developer who knows it is disposable).
    rmSync(path.join(root, DEST_DIR), { recursive: true, force: true });
    expect(existsSync(path.join(root, DEST_DIR))).toBe(false);

    const second = syncKnowledgeObsidian(root);
    expect(second.ok).toBe(true);
    expect(listDestFiles()).toEqual(firstListing);
    expect(readFileSync(path.join(root, DEST_DIR, "nodes/a.md"), "utf8")).toBe(
      firstContent
    );
  });

  test("re-sync is a clean rebuild: a file removed from staging disappears from DEST_DIR", () => {
    stage("nodes/a.md", "# a\n");
    stage("nodes/stale.md", "# will be removed from staging\n");

    expect(syncKnowledgeObsidian(root).ok).toBe(true);
    expect(listDestFiles()).toContain("nodes/stale.md");

    rmSync(path.join(root, STAGING_DIR, "nodes/stale.md"));

    expect(syncKnowledgeObsidian(root).ok).toBe(true);
    const after = listDestFiles();
    expect(after).not.toContain("nodes/stale.md");
    expect(after).toContain("nodes/a.md");
  });
});

describe("CLI entry point posture (staging absent)", () => {
  test("syncKnowledgeObsidian on an empty staging tree copies nothing and fails closed on nothing", () => {
    const outcome = syncKnowledgeObsidian(root);
    expect(outcome.ok).toBe(true);
    if (!outcome.ok) throw new Error("unreachable");
    expect(outcome.copied).toBe(0);
  });
});

describe("real graphify obsidian export shape, sanity-checked", () => {
  test("a directory tree mimicking graphify export obsidian --dir syncs cleanly", () => {
    // Mirrors what `graphify export obsidian` actually produces: an
    // `index.md`, one note per node under `nodes/`, and (deliberately, to
    // prove the file-type rule earns its keep on the real export shape) a
    // generated `.obsidian/` config directory that must never be copied.
    stage("index.md", "# Graph index\n");
    stage("nodes/withTenant.md", "# withTenant\n");
    stage("nodes/authorizeInTransaction.md", "# authorizeInTransaction\n");
    stage(".obsidian/workspace.json", "{}");
    stage(".obsidian/app.json", "{}");

    const outcome = syncKnowledgeObsidian(root);
    expect(outcome.ok).toBe(false);
    if (outcome.ok) throw new Error("unreachable");
    expect(outcome.violations.every((v) => v.rule === "file-type")).toBe(true);
  });
});
